# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates


# Add different package-ecosystems (list on github) and list the directory of where the files to fix that stuff would be, called the package manifest.

version: 2
updates:
#   - package-ecosystem: "" # See documentation for possible values
#     directory: "/" # Location of package manifests
#     schedule:
#       interval: "daily"
      
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests. LOOK AT
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
